# Schema for the configuration files of the My Config Forms module.
my_config_forms.settings:
  type: config_object
  label: 'My Config Forms settings'
  mapping:
    example:
      type: string
      label: 'Example'

# Schema for the configuration files of the My Config Forms module.
my_config_forms_ajax.settings:
  type: config_object
  label: 'My Config Forms settings'
  mapping:
    example:
      type: string
      label: 'Example'

# Schema for the configuration files of the My Config Forms module.
my_config_forms_reset.settings:
  type: config_object
  label: 'My Config Forms settings'
  mapping:
    example:
      type: string
      label: 'Example'
